### ISSUE TITLE
Go-Live Roadmap

### ISSUE THREAD

**Issue by aRusenov** [edcast/leapest-photon#2]
- [ ] Api resolver
- [ ] User authentication & authorization
- [ ] Redis for api + system
- [ ] Logger (json, similar to new logback for kibana)
- [ ] Error handling
- [ ] Migration script from mongo to mysql
- [ ] Tests
